### PR TITLE
Avoid using the python3 await keyword

### LINKED ISSUE #60: if you try to use await as a variable or function name, this will cause a SyntaxError if your code is for Python 3.7 or later.
```
raceback (most recent call last):                                                                       
  File "/usr/lib/python3.8/py_compile.py", line 144, in compile
    code = loader.source_to_code(source_bytes, dfile or file,    
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/Timba/Apps/app_proxy.py", line 332
    res = self._pwp.await('*',resume=True,timeout=5);  # await anything, but keep looping until status changes
                    ^                                                                                                                                                                                              
SyntaxError: invalid syntax                                                                              

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/py_compile.py", line 197, in main
    compile(filename, doraise=True)
  File "/usr/lib/python3.8/py_compile.py", line 150, in compile
    raise py_exc                                    
__main__.PyCompileError:   File "/usr/lib/python3/dist-packages/Timba/Apps/app_proxy.py", line 332
    res = self._pwp.await('*',resume=True,timeout=5);  # await anything, but keep looping until status changes
                    ^                               
SyntaxError: invalid syntax
```

### PR DESCRIPTION
**Pull request by Athanaseus**
resolves #60

### CODE REVIEW

File: MeqNodes/src/FFTBrick.cc [hunk 1]
```diff
@@ -244,7 +244,7 @@ inline void copyDoubleToComplex (
   blitz::Array<dcomplex,2>::iterator iter_out = out1.begin();
   blitz::Array<double,2>::iterator iter_in = in1.begin();
   for( ; iter_out != out1.end(); ++iter_out,++iter_in)
-    *iter_out = *iter_in + 0.i;
+    *iter_out = *iter_in + 0;
```
Comment (bennahugo) [inline MeqNodes/src/FFTBrick.cc:247]: Why this change to float point? This should implicitly cast to complex

**Review by bennahugo — CHANGES_REQUESTED** [review]

**Comment by bennahugo** [comment]
ok to test

File: MeqNodes/src/FFTBrick.cc (hunk 1 above)
Comment (Athanaseus) [reply MeqNodes/src/FFTBrick.cc:247]: This relates to https://github.com/ska-sa/meqtrees-timba/commit/49b1f1b1c2c2d40c562b83d940f44ef4db17a3ca

When i reverted my accidental changes I reverted this changes too. So here I'm trying to take things back to how there where

**Review by bennahugo — APPROVED** [review]
